name: 'Gu-ZT/toml-reader'
description: 'Read a specific field from a TOML file'
branding:
  icon: file-text
  color: gray-dark
inputs:
  file:
    description: 'The TOML file to read from'
    required: true
  fields:
    description: 'The fields inside the TOML file to read'
    required: true
  split:
    description: 'The character to split the field name (e.g., "_", "-")'
    required: false
    default: '_'
  debug:
    description: 'Whether to enable debug mode (true/false)'
    required: false
    default: 'false'
runs:
  using: 'node20'
  main: 'index.js'
