name: Test for TOML Reader Action
on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Read TOML
        id: 'properties'
        uses: Gu-ZT/toml-reader-action@main
        with:
          debug: true
          file: .github/test/test.toml
          fields: |
            package.name
            package.version
            dependencies.foo
            dependencies.bar # 不存在的字段

      - name: Show properties
        run: |
          echo "outputs: ${{ steps.properties.outputs }}"
          echo "Package Name: ${{ steps.properties.outputs.package_name }}"
          echo "Package Version: ${{ steps.properties.outputs.package_version }}"
          echo "Dependency Foo: ${{ steps.properties.outputs.dependencies_foo }}"
          echo "Dependency Bar: ${{ steps.properties.outputs.dependencies_bar }}"